export type PayeeSeed = {
  name: string
  defaultCategoryName: string | null
}

export const payees: PayeeSeed[] = [
  { name: "Loblaws", defaultCategoryName: "🛒 Groceries" },
  { name: "Costco", defaultCategoryName: "🛒 Groceries" },
  { name: "Farm Boy", defaultCategoryName: "🛒 Groceries" },
  { name: "Metro", defaultCategoryName: "🛒 Groceries" },
  { name: "Walmart", defaultCategoryName: "🛒 Groceries" },
  { name: "Shoppers Drug Mart", defaultCategoryName: "💊 Pharmacy" },
  { name: "Tim Hortons", defaultCategoryName: "☕ Coffee Shops" },
  { name: "Starbucks", defaultCategoryName: "☕ Coffee Shops" },
  { name: "Second Cup", defaultCategoryName: "☕ Coffee Shops" },
  { name: "Swiss Chalet", defaultCategoryName: "🍽️ Restaurants" },
  { name: "Shawarma Palace", defaultCategoryName: "🍽️ Restaurants" },
  { name: "Restaurant", defaultCategoryName: "🍽️ Restaurants" },
  { name: "SkipTheDishes", defaultCategoryName: "📦 Food Delivery" },
  { name: "DoorDash", defaultCategoryName: "📦 Food Delivery" },
  { name: "Shell", defaultCategoryName: "⛽ Gas" },
  { name: "Petro-Canada", defaultCategoryName: "⛽ Gas" },
  { name: "Canadian Tire", defaultCategoryName: "🔨 Home Maintenance" },
  { name: "Home Depot", defaultCategoryName: "🔨 Home Maintenance" },
  { name: "IKEA", defaultCategoryName: "🪑 Furniture & Decor" },
  { name: "Amazon", defaultCategoryName: "🛒 Online Shopping" },
  { name: "Winners", defaultCategoryName: "👕 Clothing" },
  { name: "Sport Chek", defaultCategoryName: "🏋️ Sports & Fitness" },
  { name: "MEC", defaultCategoryName: "🏋️ Sports & Fitness" },
  { name: "Cineplex", defaultCategoryName: "🎬 Entertainment" },
  { name: "Netflix", defaultCategoryName: "📺 Subscriptions" },
  { name: "Spotify", defaultCategoryName: "📺 Subscriptions" },
  { name: "Apple", defaultCategoryName: "📺 Subscriptions" },
  { name: "Nintendo", defaultCategoryName: "🎬 Entertainment" },
  { name: "Hydro Ottawa", defaultCategoryName: "⚡ Hydro" },
  { name: "Bell Canada", defaultCategoryName: "🌐 Internet" },
  { name: "Telus", defaultCategoryName: "📱 Phone" },
  { name: "Scotiabank Mortgage", defaultCategoryName: "🏠 Mortgage" },
  { name: "TD Auto Finance", defaultCategoryName: "🚗 Car Payment" },
  { name: "Desjardins Insurance", defaultCategoryName: "📄 Auto Insurance" },
  { name: "Wealthsimple", defaultCategoryName: "📊 TFSA Contribution" },
  { name: "City of Ottawa", defaultCategoryName: "🏛️ Property Tax" },
  { name: "PetSmart", defaultCategoryName: "🐕 Mango (food & supplies)" },
  { name: "Alta Vista Animal Hospital", defaultCategoryName: "🏥 Vet" },
  { name: "Uber", defaultCategoryName: "🅿️ Parking" },
  { name: "Indigo", defaultCategoryName: "🎨 Hobbies" },
  { name: "LCBO", defaultCategoryName: "🛒 Groceries" },
  { name: "AirBnb", defaultCategoryName: "✈️ Vacation Fund" },
  { name: "e-Transfer", defaultCategoryName: null },
  { name: "ATM", defaultCategoryName: null },
  { name: "Other", defaultCategoryName: null },
  { name: "Employer - Alex", defaultCategoryName: "💰 Ready to Assign" },
  { name: "Employer - Jamie", defaultCategoryName: "💰 Ready to Assign" },
]
